package Tecnomundo;


import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Milton
 */
public class VentanaAdminProducto extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form VentanaAdminProducto
     */
    public VentanaAdminProducto(String tipo) {
        initComponents();
        
        switch(tipo){
            case "Modificar":
                configVentanaModificar();
                break;
            case "Crear":
                configVentanaCrear();
                break;
            case "Consultar":
                configVentanaConsulta();
                break;               
        }
        
        setControlador();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            
    }
    
    public void setControlador(){
        botonAdmin.addActionListener(this);
        botonCancelar.addActionListener(this);
        botonImagen.addActionListener(this);
    }  
    
    
    public void configVentanaModificar(){
        labelTitulo.setText("MODIFICAR PRODUCTO");
        botonAdmin.setText("Modificar");
        textIDProducto.setEditable(false);
    }
    
    public void configVentanaCrear(){
        labelTitulo.setText("CREAR PRODUCTO");
        botonAdmin.setText("Crear");
        
    }
    
    public void configVentanaConsulta(){
        labelTitulo.setText("CONSULTAR PRODUCTO");
        botonAdmin.setText("Continuar");
        textIDProducto.setEditable(false);
        comboCategoria.setEditable(false);
        textNombre.setEditable(false);      
        textPrecio.setEditable(false);
        textFabricante.setEditable(false);
        textIVA.setEditable(false);
        textAreaDescripcion.setEditable(false);
        //botonImagen.setEnabled(false);
        textDetalle1.setEditable(false);
        textDetalle2.setEditable(false);
        textDetalle3.setEditable(false);
        textDetalle4.setEditable(false);
        textDetalle5.setEditable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitulo = new javax.swing.JLabel();
        labelIDProducto = new javax.swing.JLabel();
        textIDProducto = new javax.swing.JTextField();
        labelCategoria = new javax.swing.JLabel();
        comboCategoria = new javax.swing.JComboBox();
        labeINombre = new javax.swing.JLabel();
        textNombre = new javax.swing.JTextField();
        labelPrecio = new javax.swing.JLabel();
        textPrecio = new javax.swing.JTextField();
        labelFabricante = new javax.swing.JLabel();
        textFabricante = new javax.swing.JTextField();
        labelDescripcion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaDescripcion = new javax.swing.JTextArea();
        labelIVA = new javax.swing.JLabel();
        textIVA = new javax.swing.JTextField();
        botonAdmin = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        panelImagen = new javax.swing.JPanel();
        labelImagen = new javax.swing.JLabel();
        botonImagen = new javax.swing.JButton();
        panelDetalles = new javax.swing.JPanel();
        labelDetalle1 = new javax.swing.JLabel();
        labelDetalle3 = new javax.swing.JLabel();
        labelDetalle2 = new javax.swing.JLabel();
        labelDetalle4 = new javax.swing.JLabel();
        labelDetalle5 = new javax.swing.JLabel();
        textDetalle1 = new javax.swing.JTextField();
        textDetalle2 = new javax.swing.JTextField();
        textDetalle3 = new javax.swing.JTextField();
        textDetalle4 = new javax.swing.JTextField();
        textDetalle5 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelTitulo.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(0, 51, 102));
        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo.setText("ADMIN PRODUCTO");

        labelIDProducto.setFont(new java.awt.Font("Kalinga", 0, 14)); // NOI18N
        labelIDProducto.setForeground(new java.awt.Color(51, 102, 255));
        labelIDProducto.setText("ID Producto:");

        textIDProducto.setFont(new java.awt.Font("Kalinga", 0, 12)); // NOI18N

        labelCategoria.setFont(new java.awt.Font("Kalinga", 0, 14)); // NOI18N
        labelCategoria.setForeground(new java.awt.Color(51, 102, 255));
        labelCategoria.setText("Categoría: ");

        comboCategoria.setFont(new java.awt.Font("Kalinga", 0, 12)); // NOI18N
        comboCategoria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        labeINombre.setFont(new java.awt.Font("Kalinga", 0, 14)); // NOI18N
        labeINombre.setForeground(new java.awt.Color(51, 102, 255));
        labeINombre.setText("Nombre:");

        textNombre.setFont(new java.awt.Font("Kalinga", 0, 12)); // NOI18N

        labelPrecio.setFont(new java.awt.Font("Kalinga", 0, 14)); // NOI18N
        labelPrecio.setForeground(new java.awt.Color(51, 102, 255));
        labelPrecio.setText("Precio:");

        textPrecio.setFont(new java.awt.Font("Kalinga", 0, 12)); // NOI18N

        labelFabricante.setFont(new java.awt.Font("Kalinga", 0, 14)); // NOI18N
        labelFabricante.setForeground(new java.awt.Color(51, 102, 255));
        labelFabricante.setText("Fabricante:");

        textFabricante.setFont(new java.awt.Font("Kalinga", 0, 12)); // NOI18N

        labelDescripcion.setFont(new java.awt.Font("Kalinga", 0, 14)); // NOI18N
        labelDescripcion.setForeground(new java.awt.Color(51, 102, 255));
        labelDescripcion.setText("Descripción:");

        textAreaDescripcion.setColumns(20);
        textAreaDescripcion.setFont(new java.awt.Font("Kalinga", 0, 12)); // NOI18N
        textAreaDescripcion.setRows(5);
        jScrollPane1.setViewportView(textAreaDescripcion);

        labelIVA.setFont(new java.awt.Font("Kalinga", 0, 14)); // NOI18N
        labelIVA.setForeground(new java.awt.Color(51, 102, 255));
        labelIVA.setText("IVA:");

        textIVA.setFont(new java.awt.Font("Kalinga", 0, 12)); // NOI18N

        botonAdmin.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        botonAdmin.setText("Ingresar");

        botonCancelar.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        botonCancelar.setText("Cancelar");

        panelImagen.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout panelImagenLayout = new javax.swing.GroupLayout(panelImagen);
        panelImagen.setLayout(panelImagenLayout);
        panelImagenLayout.setHorizontalGroup(
            panelImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 206, Short.MAX_VALUE)
        );
        panelImagenLayout.setVerticalGroup(
            panelImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 187, Short.MAX_VALUE)
        );

        labelImagen.setFont(new java.awt.Font("Kalinga", 0, 14)); // NOI18N
        labelImagen.setForeground(new java.awt.Color(51, 102, 255));
        labelImagen.setText("Imágen");

        botonImagen.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        botonImagen.setText("...");
        botonImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonImagenActionPerformed(evt);
            }
        });

        panelDetalles.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Detalles", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Consolas", 1, 18), new java.awt.Color(0, 51, 102))); // NOI18N

        labelDetalle1.setFont(new java.awt.Font("Kalinga", 0, 14)); // NOI18N
        labelDetalle1.setForeground(new java.awt.Color(51, 102, 255));
        labelDetalle1.setText("Detalle 1:");

        labelDetalle3.setFont(new java.awt.Font("Kalinga", 0, 14)); // NOI18N
        labelDetalle3.setForeground(new java.awt.Color(51, 102, 255));
        labelDetalle3.setText("Detalle 3:");

        labelDetalle2.setFont(new java.awt.Font("Kalinga", 0, 14)); // NOI18N
        labelDetalle2.setForeground(new java.awt.Color(51, 102, 255));
        labelDetalle2.setText("Detalle 2:");

        labelDetalle4.setFont(new java.awt.Font("Kalinga", 0, 14)); // NOI18N
        labelDetalle4.setForeground(new java.awt.Color(51, 102, 255));
        labelDetalle4.setText("Detalle 4:");

        labelDetalle5.setFont(new java.awt.Font("Kalinga", 0, 14)); // NOI18N
        labelDetalle5.setForeground(new java.awt.Color(51, 102, 255));
        labelDetalle5.setText("Detalle 5:");

        textDetalle1.setFont(new java.awt.Font("Kalinga", 0, 12)); // NOI18N

        textDetalle2.setFont(new java.awt.Font("Kalinga", 0, 12)); // NOI18N

        textDetalle3.setFont(new java.awt.Font("Kalinga", 0, 12)); // NOI18N

        textDetalle4.setFont(new java.awt.Font("Kalinga", 0, 12)); // NOI18N

        textDetalle5.setFont(new java.awt.Font("Kalinga", 0, 12)); // NOI18N

        javax.swing.GroupLayout panelDetallesLayout = new javax.swing.GroupLayout(panelDetalles);
        panelDetalles.setLayout(panelDetallesLayout);
        panelDetallesLayout.setHorizontalGroup(
            panelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDetallesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDetallesLayout.createSequentialGroup()
                        .addComponent(labelDetalle1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textDetalle1, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
                    .addGroup(panelDetallesLayout.createSequentialGroup()
                        .addComponent(labelDetalle3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textDetalle3, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
                    .addGroup(panelDetallesLayout.createSequentialGroup()
                        .addComponent(labelDetalle2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textDetalle2, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
                    .addGroup(panelDetallesLayout.createSequentialGroup()
                        .addComponent(labelDetalle4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textDetalle4, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
                    .addGroup(panelDetallesLayout.createSequentialGroup()
                        .addComponent(labelDetalle5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textDetalle5, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)))
                .addGap(47, 47, 47))
        );
        panelDetallesLayout.setVerticalGroup(
            panelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDetallesLayout.createSequentialGroup()
                .addGroup(panelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelDetalle1)
                    .addComponent(textDetalle1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDetalle2)
                    .addComponent(textDetalle2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDetalle3)
                    .addComponent(textDetalle3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDetalle4)
                    .addComponent(textDetalle4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDetalle5)
                    .addComponent(textDetalle5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(labelIDProducto)
                                        .addComponent(labelCategoria)
                                        .addComponent(labeINombre)
                                        .addComponent(labelPrecio)
                                        .addComponent(labelFabricante)
                                        .addComponent(labelIVA))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelDescripcion)
                                        .addGap(11, 11, 11)))
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(textIDProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                                        .addComponent(comboCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(textNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                                        .addComponent(textPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                                        .addComponent(textFabricante, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                                        .addComponent(textIVA))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(botonAdmin)
                                .addGap(89, 89, 89)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(botonCancelar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(labelImagen)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(botonImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(panelDetalles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(panelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelIDProducto)
                            .addComponent(textIDProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelCategoria)
                            .addComponent(comboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labeINombre)
                            .addComponent(textNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelPrecio)
                            .addComponent(textPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelFabricante)
                            .addComponent(textFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelIVA)
                            .addComponent(textIVA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelImagen))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(botonImagen)))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelDescripcion)
                    .addComponent(panelDetalles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAdmin)
                    .addComponent(botonCancelar))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonImagenActionPerformed
         // TODO add your handling code here:
    }//GEN-LAST:event_botonImagenActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAdmin;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonImagen;
    private javax.swing.JComboBox comboCategoria;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labeINombre;
    private javax.swing.JLabel labelCategoria;
    private javax.swing.JLabel labelDescripcion;
    private javax.swing.JLabel labelDetalle1;
    private javax.swing.JLabel labelDetalle2;
    private javax.swing.JLabel labelDetalle3;
    private javax.swing.JLabel labelDetalle4;
    private javax.swing.JLabel labelDetalle5;
    private javax.swing.JLabel labelFabricante;
    private javax.swing.JLabel labelIDProducto;
    private javax.swing.JLabel labelIVA;
    private javax.swing.JLabel labelImagen;
    private javax.swing.JLabel labelPrecio;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JPanel panelDetalles;
    private javax.swing.JPanel panelImagen;
    private javax.swing.JTextArea textAreaDescripcion;
    private javax.swing.JTextField textDetalle1;
    private javax.swing.JTextField textDetalle2;
    private javax.swing.JTextField textDetalle3;
    private javax.swing.JTextField textDetalle4;
    private javax.swing.JTextField textDetalle5;
    private javax.swing.JTextField textFabricante;
    private javax.swing.JTextField textIDProducto;
    private javax.swing.JTextField textIVA;
    private javax.swing.JTextField textNombre;
    private javax.swing.JTextField textPrecio;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent ae) {
        if(ae.getActionCommand().equals("Modificar")){
            JOptionPane.showMessageDialog(null, "Implementame! D:");
        }
        
        if(ae.getActionCommand().equals("Continuar")){
            JOptionPane.showMessageDialog(null, "Implementame! D:");
            this.dispose();
        }
        
        if(ae.getActionCommand().equals("Crear")){
            JOptionPane.showMessageDialog(null, "Implementame! D:");
        }
        
        if(ae.getActionCommand().equals("...")){
            JOptionPane.showMessageDialog(null, "Implementame! D:");
        }
        
        if(ae.getActionCommand().equals("Cancelar")){
            this.dispose();
        }
    }
}
